USE z1726017;

CREATE TABLE USER(
    USERNAME CHAR(20) PRIMARY KEY,
    PHONE    CHAR(15) NOT NULL
);

CREATE TABLE STORE(
    STORE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME CHAR(20),
    ADDRESS CHAR(45)
);

CREATE TABLE EMPLOYEES(
    USERNAME CHAR(20),
    STORE_ID INT,
    OWNER BOOL,

    PRIMARY KEY(USERNAME, STORE_ID),
    FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
    FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID)
);

CREATE TABLE INVENTORY(
    PROD_ID   INT AUTO_INCREMENT PRIMARY KEY UNIQUE, 
    PROD_NAME CHAR(15),
    PRICE     DECIMAL(7,2)
);

CREATE TABLE STORE_INVENTORY(
    STORE_ID INT,
    PROD_ID INT,
    STOCK INT,

    PRIMARY KEY (STORE_ID, PROD_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
    FOREIGN KEY (PROD_ID) REFERENCES INVENTORY(PROD_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID      INT AUTO_INCREMENT,
    USERNAME      CHAR(20),
    PAID_AMOUNT   DECIMAL(7,2),
    TRACK_NUM     INT,
    ORDSTATUS     CHAR(10),
    CREDNUM       CHAR(16),
    CVC           INT,
    EXPDATE       CHAR(5),
    ADDR          CHAR(45),

    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
);

CREATE TABLE ORDER_INVENTORY(
    ORDER_ID INT,
    PROD_ID INT,
    STORE_ID INT,

    PRIMARY KEY(ORDER_ID, PROD_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PROD_ID) REFERENCES INVENTORY(PROD_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);

CREATE TABLE SHOPPING_CART(
    CART_ID        INT AUTO_INCREMENT,
    USERNAME      CHAR(20),
    CURRENT_TOTAL  INT NULL,

    PRIMARY KEY (CART_ID),
    FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
);

CREATE TABLE INVENTORYINCART(
    PROD_ID     INT,
    CART_ID     INT,
    STORE_ID    INT,
    QTY         INT,

    PRIMARY KEY(PROD_ID, CART_ID),
    FOREIGN KEY (PROD_ID) REFERENCES INVENTORY(PROD_ID),
    FOREIGN KEY (CART_ID) REFERENCES SHOPPING_CART(CART_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);

SELECT *
FROM INVENTORYINCART
INNER JOIN SHOPPING_CART ON SHOPPING_CART.CART_ID = INVENTORYINCART.CART_ID
INNER JOIN INVENTORY ON INVENTORYINCART.PROD_ID = INVENTORY.PROD_ID
INNER JOIN STORE_INVENTORY ON STORE_INVENTORY.PROD_ID = INVENTORYINCART.PROD_ID
WHERE SHOPPING_CART.USERNAME = 'Kyle';