

CXX = g++
CXXFLAGS = -Wall -std=c++11

z1913104_project1: z1913104_project1.o
	$(CXX) $(CXXFLAGS) -o z1913104_project1 $^

z1913104_project1.o: z1913104_project1.cpp

clean:
	rm -f z1913104_project1 *.o


