CXX = g++
CXXFLAGS = -Wall -std=c++11

z1913104_project2: z1913104_project2.o
	$(CXX) $(CXXFLAGS) -o z1913104_project2 $^

z1913104_project2.o: z1913104_project2.cpp

clean:
	rm -f z1913104_project2 output.txt fcfs.output *.o
